<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>dox</string>
  </array>
  <key>name</key>
  <string>Doxygen</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>begin</key>
      <string>(^\@(code|cond|dot|htmlonly|if|internal|latexonly|link|manonly|msc|rtfonly|verbatim|xmlonly))</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>keyword.source.doxygen</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(^\@end[A-Za-z]+)</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.source.doxygen</string>
        </dict>
      </dict>
      <key>name</key>
      <string>string.source.doxygen</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
        <dict>
          <key>match</key>
          <string>.</string>
          <key>name</key>
          <string>string.doxygen</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>begin</key>
      <string>(^\\(code|cond|dot|htmlonly|if|internal|latexonly|link|manonly|msc|rtfonly|verbatim|xmlonly))</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>keyword.source.doxygen</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(^\\end[A-Za-z]+)</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.source.doxygen</string>
        </dict>
      </dict>
      <key>name</key>
      <string>string.source.doxygen</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
        <dict>
          <key>match</key>
          <string>.</string>
          <key>name</key>
          <string>string.doxygen</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>comment</key>
      <string>Keyword for doxygen</string>
      <key>match</key>
      <string>^\@[A-Za-z]+</string>
      <key>name</key>
      <string>keyword.source.doxygen</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>Keyword for doxygen</string>
      <key>match</key>
      <string>^\\[A-Za-z]+</string>
      <key>name</key>
      <string>keyword.source.doxygen</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.doxygen</string>
  <key>uuid</key>
  <string>c0e2059f-c799-4ebb-a666-c54ebf7525ff</string>
</dict>
</plist>
